[project]
name = "gas-burn-by-site"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.0",
    "mssql>=1.0.1",
    "mssql-python>=1.11.0",
    "nbdev>=3.2.2",
    "nbdevauto>=0.3.26",
    "numpy>=2.5.1",
    "pandas>=3.0.3",
    "requests>=2.34.2",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
    "urllib3>=2.7.0",
]
